services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build # Target the build stage for development
    volumes: # Mount volumes for development
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./webpack.config.js:/app/webpack.config.js # Mount webpack config
    ports:
      - "3000:3000" # Map host 3000 to container dev server port 3000
    environment:
      NODE_ENV: development # Set environment to development
      CHOKIDAR_USEPOLLING: "true" # Often needed for Docker volume hot-reloading
      MOCK_API_URL: "http://mock_api:3001" # Add explicit URL for mock API
    networks:
      - app-network
    command: npm run dev
    depends_on:
      - mock_api

  mock_api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./mock-api:/app/mock-api
    command: >
      sh -c "npm install -g json-server && 
             json-server --watch mock-api/db.json --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge
